CREATE DATABASE Applemusic;
USE Applemusic;

CREATE TABLE users (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15)
);

CREATE TABLE artists (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    `language` VARCHAR(255) NOT NULL
);

CREATE TABLE songs (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    artist INTEGER NOT NULL,
    FOREIGN KEY (artist) REFERENCES artists(id) ON DELETE RESTRICT
);

CREATE TABLE albums (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    artist INTEGER NOT NULL, 
    FOREIGN KEY (artist) REFERENCES artists(id) ON DELETE RESTRICT
);

CREATE TABLE playlists (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255),
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);